# Generated by Django 4.1.1 on 2022-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('athor', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('accept', models.BooleanField()),
            ],
        ),
    ]
